services:
  database:
    image: postgres:15.3
    volumes:
      - database-without-celery:/var/lib/postgresql/data
    env_file:
      - .env
  
  scraping:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - database
    command: python main.py
    volumes:
      - ./src:/src
    restart: always
      
volumes:
  database-without-celery: